### ISSUE TITLE
Thank you for making the scraper. I can't figure out how this works. How to use it? Could you provide more documentation?

### ISSUE THREAD

**Issue by athang11** [JuniorJDS/Crowler_Sofa_Score#1]

**Comment by JuniorJDS** [comment]
Hi athang11. in this week I'ii fix this scraper and improve the documentation

**Comment by JuniorJDS** [comment]
Hi @athang11 , i update the doc. Now, you can run the crawler.  Anything else talk to me!

**Comment by athang11** [comment]
Thank you. It is working now.
How to use this scraper for other leagues? I can't get the links as you
have put in the sofa_scoure_2019A.py file in url_attack variable from the
website.
